user_input:
  update_data: False
  currency_pairs: 
    - EURUSD
    - GBPUSD
    - USDCHF
    - AUDUSD
    - USDCAD
    - USDJPY
  time_frames:
    - 2m
    - 5m
    - 10m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    

pathes:
  data_path: data
  graph_path: graphs
